export const commonTypes={
    LOAD_MENU_LIST:'COMMON_LOAD_MENU_LIST',
    LOAD_IMG_LIST:'COMMON_LOAD_IMG_LIST',
    CHANGE_MENU_KEY:'COMMON_CHANGE_MENU_KEY',
    TOGGLE_INFOR_MODAL:"COMMON_TOGGLE_INFOR_MODAL",
    SUBMIT_SORT_MENU:'COMMON_SUBMIT_SORT_MENU',
    CHANGE_LOGO_INFO:"COMMON_CHANGE_LOGO_INFO",
}
//首页版块
export const homeTypes ={
    LOAD_HOME_NEWS_LIST:'LOAD_HOME_NEWS_LIST',
    CHANGE_INFOR_MESSAGE:'CHANGE_INFOR_MESSAGE',
    LOAD_BANNER_LIST:'LOAD_BANNER_LIST',
    ADD_SAVEBANNER_LOAD:'ADD_SAVEBANNER_LOAD',
    MOVE_SAVEBANNER_LOAD:'MOVE_SAVEBANNER_LOAD',
    CHANGE_ADVANCE_INFOR:"CHANGE_ADVANCE_INFOR",
    CHANGE_HOME_PRODUCT_INFOR:'CHANGE_HOME_PRODUCT_INFOR',
    LOAD_HOME_NEWS_DETAIL:'LOAD_HOME_NEWS_DETAIL',
    HOME_NEWS_LOADING:'HOME_NEWS_LOADING'
}
//新闻版块
export const newsTypes={
    NEWS_LIST:'NEWS_LIST',
    NEWS_DETAIL:'NEWS_DETAIL',
    ADD_AND_EDIT:'NEWS_ADD_AND_EDIT',
    CHANGE_INFOR_TOPTITLE:"NEWS_CHANGE_INFOR_TOPTITLE",
    CHANGE_INFOR_TOPIMG:"NEWS_CHANGE_INFOR_TOPIMG",
    CHANGE_NEWS_LIST_TITLE:"CHANGE_NEWS_LIST_TITLE"

}
//联系我们版块
export const connectType={
    CHANGE_MAP:'CONNECT_CHANGE_MAP',
    CHANGE_INFOR_TITLE:"CONNECT_CHANGE_INFOR_TITLE",
    CHANGE_CONNECT_INFOR:"CONNECT_CHANGE_CONNECT_INFOR",
    CHANGE_INFOR_TOPTITLE:"CONNECT_CHANGE_INFOR_TOPTITLE",
    CHANGE_INFOR_TOPIMG:"CONNECT_CHANGE_INFOR_TOPIMG",
    CHANGE_ICON_PIC:"CONNECT_CHANGE_ICON_PIC"
}
//产品版块
export const productType={
    PRODUCT_LIST:"PRODUCT_PRODUCT_LIST",
    CHANGE_INFOR_TITLE:"PRODUCT_CHANGE_INFOR_TITLE",
    CHANGE_PRODUCT_INFOR:"PRODUCT_CHANGE_PRODUCT_INFOR",
    CHANGE_INFOR_TOPTITLE:"PRODUCT_CHANGE_INFOR_TOPTITLE",
    CHANGE_INFOR_TOPIMG:"PRODUCT_CHANGE_INFOR_TOPIMG",
    CHANGE_ICON_PIC:"PRODUCT_CHANGE_ICON_PIC",
    NEW_LIST_PRODUCT:"NEW_LIST_PRODUCT",
    CHANGE_PRODUCT_LIST_TITLE:"CHANGE_PRODUCT_LIST_TITLE"
}
//关于我们版块
export const aboutType={
    CHANGE_INFOR_TOPTITLE:"ABOUT_CHANGE_INFOR_TOPTITLE",
    CHANGE_INFOR_TOPIMG:"ABOUT_CHANGE_INFOR_TOPIMG",
    CHANGE_ICON_PIC:"ABOUT_CHANGE_ICON_PIC",
    CHANGE_ABOUT_INFOR:"CHANGE_ABOUT_INFOR",
    CHANGE_ABOUT_SERVICE:"CHANGE_ABOUT_SERVICE",
    CHANGE_ICON_PIC_SERVICE:"CHANGE_ICON_PIC_SERVICE",
    CHANGE_ICON_PIC_TEAM:"CHANGE_ICON_PIC_TEAM",
    CHANGE_ABOUT_TEAM:"CHANGE_ABOUT_TEAM",
    CHANGE_TEAM_TITLE:"CHANGE_TEAM_TITLE",
    CHANGE_TEAM_CONTENT:"CHANGE_TEAM_CONTENT",
    CHANGE_SERVICE_TITLE:"CHANGE_SERVICE_TITLE",
    CHANGE_SERVICE_CONTENT:"CHANGE_SERVICE_CONTENT"
}